### ISSUE TITLE
Does not work with svelte 2.0

### ISSUE THREAD

**Issue by burkostya** [RobBrazier/svelte-awesome#199]
Will you upgrade to support Svelte 2.x?

**Comment by RobBrazier** [comment]
Yep, sorry - haven't had much time to work on this recently. 
You can probably see a tonne of PRs from dependabot. I just need to get through those, I'll try and get a release out before monday :)

**Comment by RobBrazier** [comment]
:tada: This issue is resolved in version 1.3.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/svelte-awesome)
- [GitHub release](https://github.com/RobBrazier/svelte-awesome/releases/tag/v1.3.0)

I tested it out on my example project - https://robbrazier.github.io/svelte-awesome/ and all looks good from here :smile:

Feel free to reopen the issue if you're having problems with the new version
