### ISSUE TITLE
Tree Shaking?

### ISSUE THREAD

**Issue by InstanceOfMichael** [RobBrazier/svelte-awesome#483]
Does this library support tree shaking for Font Awesome 4? If not, tree shaking might be easier to implement in Font Awesome 5.

The most important part of tree shaking Font Awesome 4 IMO is not actually tree shaking the CSS, but tree shaking the 1 MB font files included. http://fontello.com/ does this pretty well but requires you to manually pick your icons ahead of time (but at least supports a config file) and also they randomly rename them from FA4 without keeping the original names as aliases for the search.

**Comment by RobBrazier** [comment]
In the current version, I don't think it does, however once I resolve my CI issues, the version that works with svelte 3 should support tree shaking (if I understand it correctly)

**Comment by InstanceOfMichael** [comment]
I just checked the source code, it does look like it could already be tree shaked, if the user skipped importing `import './icons';`, and that's assuming the svelte compilter or webpack/rollup isn't also going the extra mile.

**Comment by RobBrazier** [comment]
Closing as tree shaking is supported since v2.x, you only import what you need.
As the icon rendering is via svg, it only imports what's needed (and I've seen that the svelte compiler tree-shakes successfully if the user imports the entire icons index)

feel free to re-open/raise another issue if you are seeing tree-shaking not functioning properly
