### ISSUE TITLE
Icons not exported

### ISSUE THREAD

**Issue by ksmarty** [RobBrazier/svelte-awesome#643]
Hi there!

I've installed all of the @fortawesome npm packages and installed it just as in the README. I get the following error when running a dev build.

```
Error: 'faGithub' is not exported by node_modules/@fortawesome/free-brands-svg-icons/index.js
```

If you need more information, please let me know.

Thank you!

**Comment by RobBrazier** [comment]
What's the exact line that you are using to import free-brands-svg-icons?

**Comment by ksmarty** [comment]
```
import { faGoogle, faGithub } from "@fortawesome/free-brands-svg-icons";
```

**Comment by RobBrazier** [comment]
According to what you've sent, that should work, there might be something up with your build tool (rollup?), or maybe your node_modules are corrupted somehow (I know it's vague but I'm guessing here)

Apologies for being a bit blunt, but from the information you've given this doesn't look like a problem with this package (something is up with the `@fortawesome` package).

I checked their docs and it shows the import that you're doing [in the getting started page](https://fontawesome.com/how-to-use/javascript-api/setup/getting-started)

Unfortunately I can't really give support for their package. Might be worth reading their documentation more or raising a ticket on their repository if you're still getting the issue.

Even having a look at the free-brands-svg-icons/index.js file might give you some pointers.

Due to the above reasons I'm closing this issue.
