### ISSUE TITLE
Don't set inline style when unused

### ISSUE THREAD

**Issue by mhatvan** [RobBrazier/svelte-awesome#692]
I am currently trying to implement CSP with Sapper and running into issues where svelte-awesome is setting empty style attributes like here: `<svg version="1.1" class="fa-icon svelte-1x7upcw" width="15.5" height="16" role="presentation" viewBox="0 0 496 512" style="">`

My CSP policy forbids to use inline styles and this style attribute is redundant, so it would be great to adapt this in the codebase.

**Comment by RobBrazier** [comment]
really sorry for the delay, should be fixed in v2.3.2 which will be published shortly

**Comment by Newex** [comment]
This bug seems to be back... it sets an empty style even when it is not defined.

This breaks my Content-Security-Policy because I don't really want to enable 'unsafe-inline' directive.

My packages:
- sveltejs/kit 1.5.0
- svelte-awesome 3.2.0
- font awesome (@fortawesome/free-solid-svg-icons) 6.4.0
- and fontawesome-free 6.4.0
- and fontawesome-svg-core 6.4.0

Error message (chrome)
![image](https://github.com/RobBrazier/svelte-awesome/assets/14085306/fe6ab779-4bf2-444a-b54a-990708a687ba)

Element window

![image](https://github.com/RobBrazier/svelte-awesome/assets/14085306/e9987d07-66bd-4efc-8639-73b5419833ce)

Source

![image](https://github.com/RobBrazier/svelte-awesome/assets/14085306/0035b303-8ec8-4e8e-8ec5-a20af2ae44ca)
